services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-local
    ports:
      - "5672:5672" # Porta padrão para AMQP
      - "15672:15672" # Porta para a interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mspublisher1:
    build: ./ms_publisher_1
    ports:
      - "4000:4000" # Porta padrão para AMQP
    depends_on:
      rabbitmq:
        condition: service_healthy
    # Para facilitar testes, se desejar que o publisher seja executado ao iniciar o container;
    # lembre-se que ele termina após enviar a mensagem.
    container_name: mspublisher1

  mspublisher2:
    build: ./ms_publisher_2
    ports:
      - "4001:4001" # Porta padrão para AMQP
    depends_on:
      rabbitmq:
        condition: service_healthy
    # Para facilitar testes, se desejar que o publisher seja executado ao iniciar o container;
    # lembre-se que ele termina após enviar a mensagem.
    container_name: mspublisher2

  mssubscriber:
    build: ./ms_subscriber
    depends_on:
      rabbitmq:
        condition: service_healthy
    container_name: mssubscriber
